### ISSUE TITLE
关于导入后Can't resolve 'fs'

### ISSUE THREAD

**Issue by myetear** [tuzhanai/captcha#2]
请问这个问题怎么解决？？
```
ERROR in ./NOde_modules/gd-bmp/dist/BMP24.js
Module not found: Error: Can't resolve 'fs' in 'E:\tongda-angular\node_modules\gd-bmp\dist'
```
![TIM图片20190328204714](https://user-images.githubusercontent.com/48012367/55158866-da40bd00-519a-11e9-9352-63ac31d56467.jpg)

**Comment by ldezho** [comment]
@myetear 请问您怎么解决的？

**Comment by myetear** [comment]
> @myetear请问您怎么解决的？

没解决掉，我用了另一个 https://github.com/myour-cc/code-validator 或许你可以试试。

**Comment by ldezho** [comment]
@myetear 多谢，我也是换的这个
